name: Deploy to Netlify

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # or your preferred version

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build # replace with your actual build command

      - name: Deploy to Netlify
        run: |
          pnpm install -g netlify-cli
          netlify deploy --dir=dist/gramaphor/browser --prod --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
